# Generated by Django 3.0.6 on 2020-05-22 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=10)),
                ('user_image', models.FileField(upload_to='uploads/')),
                ('password', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('e_mail', models.EmailField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('NONE', 'Undefiniert'), ('MALE', 'Männlich'), ('FEMALE', 'Weiblich'), ('OTHER', 'Weitere')], default='NONE', max_length=30)),
                ('street', models.CharField(max_length=30)),
                ('house_number', models.CharField(max_length=5)),
                ('post_code', models.IntegerField(max_length=5)),
                ('domicile', models.CharField(max_length=30)),
            ],
        ),
    ]
